- hosts: all
  vars:
    webPackage: "httpd"
    docRoot: "/var/www/html"
    webService: "httpd"
    isStart: "started"
  tasks:
    - name: "install httpd software"
      package: 
       name: "{{ webPackage }}"
       state: present
      register: packageRegister

    - name: "copy index.html file for web server"
      copy:
       src: "index.html"
       dest: "{{ docRoot }}/index.html"

    - name: "start the httpd service"
      service:
       name: "{{ webService }}"
       state: "{{ isStart }}"
